### ISSUE TITLE
https:// or ipfs:// or both

### ISSUE THREAD

**Issue by mgoelzer** [ipfs/conference#26]
Goal of this issue is to debate-then-decide whether IPFS Conf website should be:
1.  Available only on an `https://` uri (presumably most conducive to a quick launch)
2.  Available at both an `ipfs://` and normal `https://` uri (approachable for newcomers)
3.  Available **only** at an `ipfs://` uri (most pure approach)

I don't believe there is currently a consensus about this.  If we could reach a decision in this issue, it can feed back into #25 .

@VictorBjelkholm @flyingzumwalt @luisptorres @dignifiedquire

**Comment by luisptorres** [comment]
I think this decision should be up to you. But given the time constraints, I would advise to have the https ready first (as a fallback) and then we focus on the ipfs assuming everything goes as expected. Then you can decide which ones you want to keep.

By the way, we have the https deployment process done already, we just need your domain to connect with gh-pages. It's really a straightforward process, you can check it in our repo if you want.

**Comment by VictorBjelkholm** [comment]
@luisptorres where is the repository at? This repository seems empty and I couldn't find any other repository within the `ipfs` org with the code?

As long as we end up with a directory of static files + relative links, we're good to go.

**Comment by jfranciscosousa** [comment]
You can take a look here at https://github.com/jfranciscosousa/ipfsconf, we just created the boilerplate for development. 

`bin/deploy` does that as I explained in #25

**Comment by flyingzumwalt** [comment]
@VictorBjelkholm is our deploy process documented somewhere? We use Hugo, right?

@mgoelzer  If you publish assets (like a website) on ipfs you can also set up a dns entry that maps a regular http domain to the root of that asset. This puts the ipfs hash in the DNS entry instead of the url, allowing people to access ipfs-based content using regular, familiar, human-readable URIs. It also let’s you set up SSL certs for that domain, giving you the ability to serve ipfs content over https as well as http and ipfs.

**Comment by dignifiedquire** [comment]
As far as I understand #27, once that is ready to go in (just missing fixes for relative paths) we will have both `ipfs` and `https` ready to be used with no additional overhead.
